//! Build-time codegen for the bundled IK dictionaries.
//!
//! The Java reference implementation (`pizza-rs/analysis-ik`) loads four
//! plain-text dictionaries at runtime into nested HashMap-backed trie nodes
//! (`DictSegment`). We do that work once at build time and emit a compact
//! static representation that the runtime can borrow from:
//!
//! - `{lower}_data.bin`     — all term UTF-8 bytes concatenated.
//! - `{lower}_offsets.bin`  — `len(words) + 1` u32 LE values; term `i` lives
//!   in `DATA[OFFSETS[i]..OFFSETS[i+1]]`.
//! - `generated.rs`         — small first-character index (`FC` +
//!   `BUCKET_START`) so the runtime can narrow lookups before binary-searching.
//!
//! Words are sorted lexicographically (UTF-8 byte order == codepoint order),
//! so all words sharing a first character are contiguous in the offsets array.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    // Only bake the dictionaries when `embed` is enabled. Without it, dict.rs
    // builds equivalent flat/trie blobs at runtime — see `dict::rt` (no-embed).
    if env::var_os("CARGO_FEATURE_EMBED").is_none() {
        return;
    }

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let data_dir = manifest_dir.join("data");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=data");

    let gen_path = out_dir.join("generated.rs");
    let _ = fs::write(&gen_path, "// Generated by build.rs — do not edit.\n");

    let main_words = if env::var("CARGO_FEATURE_MAIN_DICT").is_ok() {
        read_dict(&data_dir.join("main.dic"))
    } else {
        Vec::new()
    };
    let quantifier_words = read_dict(&data_dir.join("quantifier.dic"));
    let stopword_words = read_dict(&data_dir.join("stopword.dic"));

    emit_dict(&out_dir, "MAIN", "main", &main_words).unwrap();
    emit_dict(&out_dir, "QUANTIFIER", "quantifier", &quantifier_words).unwrap();
    emit_dict(&out_dir, "STOPWORD", "stopword", &stopword_words).unwrap();

    // Build a compact char-level prefix trie for the main dictionary. This
    // is the hot lookup structure for CJK segmentation: each step costs
    // `O(log fanout)` where `fanout` is typically 2–5, vs `O(log bucket_size)`
    // (~55) for the flat sorted-array view.
    emit_trie(&out_dir, "MAIN", &main_words).unwrap();

    let max_chars = main_words
        .iter()
        .chain(quantifier_words.iter())
        .chain(stopword_words.iter())
        .map(|w| w.chars().count())
        .max()
        .unwrap_or(0);

    let consts = format!(
        "pub const MAIN_TERM_COUNT: usize = {};\n\
         pub const QUANTIFIER_TERM_COUNT: usize = {};\n\
         pub const STOPWORD_TERM_COUNT: usize = {};\n\
         pub const MAX_TERM_CHARS: usize = {};\n",
        main_words.len(),
        quantifier_words.len(),
        stopword_words.len(),
        max_chars
    );
    fs::OpenOptions::new()
        .append(true)
        .open(&gen_path)
        .unwrap()
        .write_all(consts.as_bytes())
        .unwrap();
}

fn read_dict(path: &Path) -> Vec<String> {
    if !path.exists() {
        return Vec::new();
    }
    let bytes = fs::read(path).unwrap();
    let text = if bytes.starts_with(&[0xEF, 0xBB, 0xBF]) {
        std::str::from_utf8(&bytes[3..]).unwrap()
    } else {
        std::str::from_utf8(&bytes).unwrap()
    };
    let mut words: Vec<String> = text
        .lines()
        .map(|l| l.trim_end_matches('\r').trim().to_string())
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .collect();
    words.sort();
    words.dedup();
    words
}

fn emit_dict(
    out_dir: &Path,
    upper: &str,
    lower: &str,
    words: &[String],
) -> std::io::Result<()> {
    let total_bytes: usize = words.iter().map(|w| w.len()).sum();
    let mut data: Vec<u8> = Vec::with_capacity(total_bytes);
    let mut offsets_bin: Vec<u8> = Vec::with_capacity((words.len() + 1) * 4);
    offsets_bin.extend_from_slice(&0u32.to_le_bytes());
    for w in words {
        data.extend_from_slice(w.as_bytes());
        offsets_bin.extend_from_slice(&(data.len() as u32).to_le_bytes());
    }
    fs::write(out_dir.join(format!("{lower}_data.bin")), &data)?;
    fs::write(out_dir.join(format!("{lower}_offsets.bin")), &offsets_bin)?;

    let mut first_chars: BTreeMap<u32, usize> = BTreeMap::new();
    for (i, w) in words.iter().enumerate() {
        if let Some(c) = w.chars().next() {
            first_chars.entry(c as u32).or_insert(i);
        }
    }
    let fcs: Vec<u32> = first_chars.keys().copied().collect();
    let mut bucket_start: Vec<u32> = fcs.iter().map(|c| first_chars[c] as u32).collect();
    bucket_start.push(words.len() as u32);

    let mut out = String::new();
    out.push_str(&format!("pub const {upper}_FC: &[u32] = &["));
    for (i, fc) in fcs.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        out.push_str(&format!("{},", fc));
    }
    out.push_str("\n];\n\n");

    out.push_str(&format!("pub const {upper}_BUCKET_START: &[u32] = &["));
    for (i, v) in bucket_start.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        out.push_str(&format!("{},", v));
    }
    out.push_str("\n];\n\n");

    out.push_str(&format!(
        "pub const {upper}_DATA: &[u8] = include_bytes!(\"{lower}_data.bin\");\n"
    ));
    out.push_str(&format!(
        "pub const {upper}_OFFSETS_BIN: &[u8] = include_bytes!(\"{lower}_offsets.bin\");\n\n"
    ));

    fs::OpenOptions::new()
        .append(true)
        .open(out_dir.join("generated.rs"))?
        .write_all(out.as_bytes())?;
    Ok(())
}

/// Build a packed char-level prefix trie for `words` and emit it as three
/// binary blobs plus a small Rust constant referring to them. Layout (CSR):
///
/// - `main_trie_nodes.bin` : `(nodes + 1) × u32 LE`. Each entry is
///   `(terminal_flag << 31) | first_edge_idx`. The sentinel at the end stores
///   only the total edge count (no terminal flag).
/// - `main_trie_edge_char.bin` : `edges × u32 LE` — codepoint label.
/// - `main_trie_edge_next.bin` : `edges × u32 LE` — destination node id.
///
/// Edges of a single node are stored contiguously and sorted by codepoint,
/// enabling `O(log fanout)` lookup per char step.
fn emit_trie(out_dir: &Path, upper: &str, words: &[String]) -> std::io::Result<()> {
    // Build the trie. Use parallel `Vec<BTreeMap>` for sorted-edge insertion.
    let mut children: Vec<BTreeMap<u32, u32>> = vec![BTreeMap::new()];
    let mut terminal: Vec<bool> = vec![false];
    for w in words {
        let mut node: u32 = 0;
        for c in w.chars() {
            let key = c as u32;
            let next = children[node as usize].get(&key).copied();
            let nid = match next {
                Some(n) => n,
                None => {
                    let new_id = children.len() as u32;
                    children.push(BTreeMap::new());
                    terminal.push(false);
                    children[node as usize].insert(key, new_id);
                    new_id
                }
            };
            node = nid;
        }
        terminal[node as usize] = true;
    }

    let n_nodes = children.len();
    let n_edges_estimate: usize = children.iter().map(|m| m.len()).sum();

    let mut nodes_bin: Vec<u8> = Vec::with_capacity((n_nodes + 1) * 4);
    let mut edge_char_bin: Vec<u8> = Vec::with_capacity(n_edges_estimate * 4);
    let mut edge_next_bin: Vec<u8> = Vec::with_capacity(n_edges_estimate * 4);
    // Capture the root's edge range so we can build a direct-lookup table
    // for it. The root typically has ~5K outgoing edges across the CJK
    // range, so the table is small (~tens of KB) and replaces the ~13-step
    // binary search at the trie root with a single array load.
    let root_first_edge: u32 = 0;
    let mut cursor: u32 = 0;
    for i in 0..n_nodes {
        let mut entry = cursor;
        if terminal[i] {
            entry |= 0x8000_0000;
        }
        nodes_bin.extend_from_slice(&entry.to_le_bytes());
        for (&c, &child) in children[i].iter() {
            edge_char_bin.extend_from_slice(&c.to_le_bytes());
            edge_next_bin.extend_from_slice(&child.to_le_bytes());
            cursor += 1;
        }
    }
    // Sentinel (no terminal flag).
    nodes_bin.extend_from_slice(&cursor.to_le_bytes());

    // Build the root direct-lookup table. Each slot holds the absolute
    // child-node id for the corresponding codepoint, or `u32::MAX` for
    // "no edge". We store node ids (not edge ids) so the hot path only
    // needs to read one `u32`, skipping the second `edge_next_at` load.
    let (root_min_u32, root_max_u32, root_index_bin): (u32, u32, Vec<u8>) = {
        let root = &children[0];
        if root.is_empty() {
            (0, 0, Vec::new())
        } else {
            let min_c = *root.keys().next().unwrap();
            let max_c = *root.keys().next_back().unwrap();
            let span = (max_c - min_c + 1) as usize;
            let mut table: Vec<u32> = vec![u32::MAX; span];
            // First edge of the root is at index 0 (we wrote root's edges
            // first), so the edge index for child `c` is `root_first_edge +
            // offset_within_root` — but since we want the destination node
            // id directly, just look it up in the BTreeMap.
            let _ = root_first_edge;
            for (&c, &child_node) in root.iter() {
                table[(c - min_c) as usize] = child_node;
            }
            let mut bin: Vec<u8> = Vec::with_capacity(span * 4);
            for v in table {
                bin.extend_from_slice(&v.to_le_bytes());
            }
            (min_c, max_c, bin)
        }
    };

    fs::write(out_dir.join("main_trie_nodes.bin"), &nodes_bin)?;
    fs::write(out_dir.join("main_trie_edge_char.bin"), &edge_char_bin)?;
    fs::write(out_dir.join("main_trie_edge_next.bin"), &edge_next_bin)?;
    fs::write(out_dir.join("main_trie_root_index.bin"), &root_index_bin)?;

    let out = format!(
        "pub const {upper}_TRIE_NODE_COUNT: usize = {};\n\
         pub const {upper}_TRIE_EDGE_COUNT: usize = {};\n\
         pub const {upper}_TRIE_NODES: &[u8] = include_bytes!(\"main_trie_nodes.bin\");\n\
         pub const {upper}_TRIE_EDGE_CHAR: &[u8] = include_bytes!(\"main_trie_edge_char.bin\");\n\
         pub const {upper}_TRIE_EDGE_NEXT: &[u8] = include_bytes!(\"main_trie_edge_next.bin\");\n\
         pub const {upper}_TRIE_ROOT_INDEX: &[u8] = include_bytes!(\"main_trie_root_index.bin\");\n\
         pub const {upper}_TRIE_ROOT_MIN: u32 = {};\n\
         pub const {upper}_TRIE_ROOT_MAX: u32 = {};\n\n",
        n_nodes,
        cursor,
        root_min_u32,
        root_max_u32,
    );
    fs::OpenOptions::new()
        .append(true)
        .open(out_dir.join("generated.rs"))?
        .write_all(out.as_bytes())?;
    Ok(())
}
